-- 1.Calculate the number of orders per month in 2018
SELECT 
MONTH(order_purchase_timestamp) AS month,
COUNT(*) AS total_orders
FROM orders
WHERE YEAR(order_purchase_timestamp)=2018
GROUP BY MONTH(order_purchase_timestamp)
ORDER BY month;

-- 2.Find the average number of products per order , grouped by customer city
SELECT c.customer_city,
ROUND(AVG(x.item_count),2) AS avg_products
FROM (
    SELECT order_id, COUNT(*) AS item_count
    FROM order_items
    GROUP BY order_id
) x
JOIN orders o ON x.order_id=o.order_id
JOIN customers c ON o.customer_id=c.customer_id
GROUP BY c.customer_city
ORDER BY avg_products DESC;

-- 3.Calculate the percentage of total revenue contributed by each product category
SELECT p.product_category,
ROUND(
SUM(oi.price)*100/(SELECT SUM(price) FROM order_items),2
) AS revenue_percentage
FROM order_items oi
JOIN products p ON oi.product_id=p.product_id
GROUP BY p.product_category
ORDER BY revenue_percentage DESC;

-- 4.Identify the correlation between product price and the number of times a product has been purchased
SELECT product_id,
ROUND(AVG(price),2) AS avg_price,
COUNT(*) AS purchase_count
FROM order_items
GROUP BY product_id
ORDER BY purchase_count DESC;

-- 5.Calculate the total revenue generated by each seller , and rank them by revenue
SELECT seller_id,
ROUND(SUM(price),2) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC;
